// Seed content. The site renders from this until Firestore has documents,
// so a fresh clone looks finished before you open the admin.
// The admin's "Seed from fallback" button copies these straight into Firestore.

export const projects = [
  {
    slug: 'sentient',
    title: 'Sentient',
    client: 'Elysian',
    year: '2026',
    category: '3D / CGI · Brand Film',
    role: 'Creative Direction · 3D · Animation',
    services: 'CGI · Motion · AI Compositing',
    cover: '/img/work-sentient.jpg',
    hero: '/img/cs-hero.jpg',
    size: 'wide',
    order: 1,
    featured: true,
    lead: 'Elysian needed a launch film that made an abstract AI product feel physical — something you could almost touch before you understood what it did.',
    body: [
      'The idea centred on a single evolving form — a material that shifts between liquid, chrome and light as the product learns. Every beat of the film maps to a stage in that learning curve.',
      'I handled the full pipeline: look development in Cinema 4D and Redshift, an AI-assisted texture and lighting exploration in ComfyUI, and the final grade and composite in After Effects.',
    ],
    fullBleed: '/img/cs-fullbleed.jpg',
    process: [
      { src: '/img/cs-frame-01.jpg', caption: 'Styleframe 01' },
      { src: '/img/cs-frame-02.jpg', caption: 'Geometry test' },
      { src: '/img/cs-frame-03.jpg', caption: 'Lighting pass' },
    ],
    wide: [
      { src: '/img/cs-ai-texture.jpg', caption: 'AI texture exploration — ComfyUI' },
    ],
    tools: ['Cinema 4D', 'Redshift', 'After Effects', 'Unreal Engine 5', 'ComfyUI', 'Photoshop'],
  },
  {
    slug: 'aura',
    title: 'Aura',
    client: '[CLIENT]',
    year: '2025',
    category: 'Product Visualisation',
    role: '3D · Look Development',
    services: 'CGI · Product Render',
    cover: '/img/work-kreo.jpg',
    hero: '/img/work-kreo.jpg',
    size: 'narrow',
    order: 2,
    featured: true,
    lead: 'A sensor unit that had to look inevitable before it existed.',
    body: [
      'Hard-surface modelling and look development in Cinema 4D, lit as a studio product shoot rather than a CG render — one large key, one cool rim, and a single accent to keep it in the family.',
    ],
    process: [],
    wide: [],
    tools: ['Cinema 4D', 'Redshift', 'Photoshop'],
  },
  {
    slug: 'neural-bloom',
    title: 'Neural Bloom',
    client: 'Self-initiated',
    year: '2025',
    category: 'AI Film · Generative',
    role: 'Direction · AI Pipeline',
    services: 'Generative · Motion',
    cover: '/img/work-neural.jpg',
    hero: '/img/work-neural.jpg',
    size: 'narrow',
    order: 3,
    featured: true,
    lead: 'A generative study in growth — thousands of filaments resolving into a single form.',
    body: [
      'Built as a ComfyUI workflow with a custom conditioning chain, then retimed and graded as a film rather than a sequence of stills.',
    ],
    process: [],
    wide: [],
    tools: ['ComfyUI', 'After Effects', 'DaVinci Resolve'],
  },
  {
    slug: 'magizh-identity',
    title: 'Magizh Identity',
    client: 'Magizh',
    year: '2025',
    category: 'Title Sequence · Motion',
    role: 'Design · Animation',
    services: 'Identity · Motion',
    cover: '/img/work-magizh.jpg',
    hero: '/img/work-magizh.jpg',
    size: 'wide',
    order: 4,
    featured: true,
    lead: 'An identity built around a single rotating form.',
    body: [
      'One mark, one material, one move — designed so it reads at any size and animates from any frame.',
    ],
    process: [],
    wide: [],
    tools: ['Cinema 4D', 'After Effects', 'Illustrator'],
  },
  {
    slug: 'elysian-interface-reel',
    title: 'Elysian — Interface Reel',
    client: 'Elysian',
    year: '2025',
    category: 'Motion · UI Animation',
    role: 'Motion Design',
    services: 'UI Animation',
    cover: '',
    order: 5,
    featured: false,
    lead: '',
    body: [],
    process: [],
    wide: [],
    tools: ['After Effects'],
  },
  {
    slug: 'splat-studies',
    title: 'Splat Studies — Volumetric Capture',
    client: 'Self-initiated',
    year: '2025',
    category: 'Experimental · Real-time',
    role: 'R&D',
    services: 'Capture · Real-time',
    cover: '',
    order: 6,
    featured: false,
    lead: '',
    body: [],
    process: [],
    wide: [],
    tools: ['Gaussian Splatting', 'Cinema 4D'],
  },
  {
    slug: 'caution-editorial',
    title: 'Caution — Fashion Editorial',
    client: '[CLIENT]',
    year: '2025',
    category: 'Photography · Fashion Film',
    role: 'Direction · Photography',
    services: 'Editorial · Grade',
    cover: '',
    order: 7,
    featured: false,
    lead: '',
    body: [],
    process: [],
    wide: [],
    tools: ['Capture One', 'Photoshop'],
  },
];

export const photos = [
  { id: 'p1', src: '/img/ph2.jpg', title: 'Caution', tag: 'Editorial', order: 1, offset: 0 },
  { id: 'p2', src: '/img/ph4.jpg', title: 'Gold & Indigo', tag: 'Campaign', order: 2, offset: 64 },
  { id: 'p3', src: '/img/ph1.jpg', title: 'Terracotta', tag: 'Portrait', order: 3, offset: 0 },
  { id: 'p4', src: '/img/ph6.jpg', title: 'Silk Study', tag: 'Editorial', order: 4, offset: 20 },
  { id: 'p5', src: '/img/ph5.jpg', title: 'Golden Hour', tag: 'Portrait', order: 5, offset: 0 },
  { id: 'p6', src: '/img/ph3.jpg', title: 'Studio Portrait', tag: 'Portrait', order: 6, offset: 40 },
];

export const labs = [
  { id: 'l1', src: '/img/lab-01.jpg', title: 'Fluid Sim 04', tool: 'Houdini', tag: 'procedural', order: 1, h: 420 },
  { id: 'l2', src: '/img/lab-06.jpg', title: 'Thin-Film Shader', tool: 'GLSL', tag: 'shaders', order: 2, h: 300 },
  { id: 'l3', src: '/img/lab-03.jpg', title: 'Chrome Study', tool: 'Redshift', tag: 'procedural', order: 3, h: 360 },
  { id: 'l4', src: '/img/lab-04.jpg', title: 'Ribbon Figure', tool: 'Cinema 4D', tag: 'character', order: 4, h: 330 },
  { id: 'l5', src: '/img/lab-02.jpg', title: 'Procedural Grid', tool: 'Houdini', tag: 'procedural', order: 5, h: 440 },
  { id: 'l6', src: '/img/lab-05.jpg', title: 'Gaussian Splat Capture', tool: 'Real-time', tag: 'real-time', order: 6, h: 300 },
];

export const expertise = [
  { n: '01', title: 'Motion Design', body: 'Brand films, title sequences, product animation and social content.' },
  { n: '02', title: '3D / CGI', body: 'Cinema 4D, Redshift, Unreal Engine, character workflows and product visualisation.' },
  { n: '03', title: 'Photography & Fashion Films', body: 'Editorial portraits, campaigns and fashion films — shot, directed and graded in studio.' },
  { n: '04', title: 'AI Creative Production', body: 'ComfyUI, AI image and video, character consistency and generative workflows.' },
  { n: '05', title: 'Creative Technology', body: 'AI-assisted pipelines, automation systems and experimental visual tooling.' },
];

export const experience = [
  { years: '2021 — Now', role: 'Founder & Creative Director — Magizh', note: 'Rental photo studio, podcast studio and content production practice.', place: 'Chennai' },
  { years: '2023 — 2026', role: 'Motion Graphic Specialist — Sentient by Elysian', note: '3D animation and video effects for product launch work.', place: 'Bengaluru' },
  { years: '2022 — 2023', role: 'Motion Graphic Designer — aimedis.io', note: 'Animation and motion graphics for a healthcare platform.', place: 'Remote' },
  { years: '2022', role: 'Motion Designer — ByFar Studios', note: 'Motion graphics and After Effects work.', place: 'Bengaluru' },
  { years: '2021 — 2022', role: 'Motion Graphic Designer — Genten', note: 'Visual concepts and motion.', place: 'Chennai' },
  { years: '2018 — 2021', role: 'Motion Graphic Designer — TAKELEAP', note: 'Visual concepts, motion and post-production.', place: 'Tamil Nadu' },
  { years: '2015 — 2018', role: 'BSc Intermedia / Multimedia — ICAT College of Design & Media', note: 'Video post-production and visual concepts.', place: 'Chennai' },
];

export const clients = ['Elysian', 'Pixelnova', 'Magizh', 'Kreo', '[CLIENT]', '[CLIENT]', '[CLIENT]', '[CLIENT]', '[CLIENT]', '[CLIENT]', '[CLIENT]', '[CLIENT]'];

export const site = {
  name: 'Raja Kannan',
  tagline: 'I shoot it — then make it unreal.',
  blurb: 'Fashion photography, motion, 3D and AI, from capture to final frame.',
  email: 'hello@rajakannan.com',
  instagram: 'https://instagram.com/rajakannan_rk',
  city: 'Chennai, India',
  showreelUrl: '',
  availability: 'Q4 2026 — brand films, campaigns and shoots.',
};
